spring:
  profiles:
    active:
    - dev
server:
  port: 6002
eureka:
  client:
    service-url:
      default-zone:
           http://localhost:7001/eureka/
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-gjh-dev
server:
  port: 6003
eureka:
  client:
    service-url:
      default-zone:
           http://127.0.0.1:7002/eureka/
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-gjh-test
server:
  port: 6004
eureka:
  client:
    service-url:
      default-zone:
           http://G34RGMC2E.logon.ds.ge.com:7003/eureka/